### ISSUE TITLE
Questions...

### ISSUE THREAD

**Issue by bbartling** [talhaanwarch/streamlit-llama#1]
@talhaanwarch nice job on the app! Looks great. 

- Can this run on GPU as well as CPU? This code appears to run WAY faster than `llama-cpp-python` bindings.

- Curious to ask if you would be interested in collaborating at all? I am working on a similar streamlit app trying to figure out how to "chat" with your own data in creating Word embeddings. https://github.com/bbartling/my-own-llm
- See [make_embeddings.py](https://github.com/bbartling/my-own-llm/blob/develop/make_embeddings.py) in my repo, its a learning experiment for me...if you are interested I could merge my into your repo on a PR or something.

**Comment by talhaanwarch** [comment]
It is using [ctransformers ](https://github.com/marella/ctransformers) . you can read how to use gpu there. For your particular use case, i would suggest you to see [this repo of mine ](https://github.com/talhaanwarch/doc_chat). Its currently based on openai, but i am working on using opensource model. Instead of flask frontend a streamlit frontend can be used.

**Comment by bbartling** [comment]
Nice work! How do you setup the demo of your app? Is that hosted on GitHub?

Very cool.

**Comment by talhaanwarch** [comment]
its hosted on vps. though the model is hosted locally

**Comment by bbartling** [comment]
Any chance you could send me a link for that hosting service?

Would you have any advice between using llama-cpp-python or ctramformers for better results?

- https://llama-cpp-python.readthedocs.io/en/latest/

**Comment by talhaanwarch** [comment]
the hosting server has no rule, the model is hosting locally. I dont think there will be much difference between both.

**Comment by bbartling** [comment]
what is VPS where you say its hosted. I cant find that vendor

**Comment by talhaanwarch** [comment]
llama model is hosted locally on my pc
